// Auto-generated from Intl.DisplayNames (en + ar) over ISO 3166-1 alpha-2 codes.
// Regenerate: node --input-type=module -e "<see PR>" . Do not hand-edit.
export type Country = { code: string; en: string; ar: string };

export const COUNTRIES: Country[] = [
  { code: "AF", en: "Afghanistan", ar: "أفغانستان" },
  { code: "AX", en: "Åland Islands", ar: "جزر آلاند" },
  { code: "AL", en: "Albania", ar: "ألبانيا" },
  { code: "DZ", en: "Algeria", ar: "الجزائر" },
  { code: "AS", en: "American Samoa", ar: "ساموا الأمريكية" },
  { code: "AD", en: "Andorra", ar: "أندورا" },
  { code: "AO", en: "Angola", ar: "أنغولا" },
  { code: "AI", en: "Anguilla", ar: "أنغويلا" },
  { code: "AQ", en: "Antarctica", ar: "أنتاركتيكا" },
  { code: "AG", en: "Antigua & Barbuda", ar: "أنتيغوا وبربودا" },
  { code: "AR", en: "Argentina", ar: "الأرجنتين" },
  { code: "AM", en: "Armenia", ar: "أرمينيا" },
  { code: "AW", en: "Aruba", ar: "أروبا" },
  { code: "AU", en: "Australia", ar: "أستراليا" },
  { code: "AT", en: "Austria", ar: "النمسا" },
  { code: "AZ", en: "Azerbaijan", ar: "أذربيجان" },
  { code: "BS", en: "Bahamas", ar: "جزر البهاما" },
  { code: "BH", en: "Bahrain", ar: "البحرين" },
  { code: "BD", en: "Bangladesh", ar: "بنغلاديش" },
  { code: "BB", en: "Barbados", ar: "بربادوس" },
  { code: "BY", en: "Belarus", ar: "بيلاروس" },
  { code: "BE", en: "Belgium", ar: "بلجيكا" },
  { code: "BZ", en: "Belize", ar: "بليز" },
  { code: "BJ", en: "Benin", ar: "بنين" },
  { code: "DY", en: "Benin", ar: "بنين" },
  { code: "BM", en: "Bermuda", ar: "برمودا" },
  { code: "BT", en: "Bhutan", ar: "بوتان" },
  { code: "BO", en: "Bolivia", ar: "بوليفيا" },
  { code: "BA", en: "Bosnia & Herzegovina", ar: "البوسنة والهرسك" },
  { code: "BW", en: "Botswana", ar: "بوتسوانا" },
  { code: "BV", en: "Bouvet Island", ar: "جزيرة بوفيه" },
  { code: "BR", en: "Brazil", ar: "البرازيل" },
  { code: "IO", en: "British Indian Ocean Territory", ar: "الإقليم البريطاني في المحيط الهندي" },
  { code: "VG", en: "British Virgin Islands", ar: "جزر فيرجن البريطانية" },
  { code: "BN", en: "Brunei", ar: "بروناي" },
  { code: "BG", en: "Bulgaria", ar: "بلغاريا" },
  { code: "BF", en: "Burkina Faso", ar: "بوركينا فاسو" },
  { code: "HV", en: "Burkina Faso", ar: "بوركينا فاسو" },
  { code: "BI", en: "Burundi", ar: "بوروندي" },
  { code: "KH", en: "Cambodia", ar: "كمبوديا" },
  { code: "CM", en: "Cameroon", ar: "الكاميرون" },
  { code: "CA", en: "Canada", ar: "كندا" },
  { code: "CV", en: "Cape Verde", ar: "الرأس الأخضر" },
  { code: "BQ", en: "Caribbean Netherlands", ar: "هولندا الكاريبية" },
  { code: "KY", en: "Cayman Islands", ar: "جزر كايمان" },
  { code: "CF", en: "Central African Republic", ar: "جمهورية أفريقيا الوسطى" },
  { code: "TD", en: "Chad", ar: "تشاد" },
  { code: "CL", en: "Chile", ar: "تشيلي" },
  { code: "CN", en: "China", ar: "الصين" },
  { code: "CX", en: "Christmas Island", ar: "جزيرة كريسماس" },
  { code: "CC", en: "Cocos (Keeling) Islands", ar: "جزر كوكوس (كيلينغ)" },
  { code: "CO", en: "Colombia", ar: "كولومبيا" },
  { code: "KM", en: "Comoros", ar: "جزر القمر" },
  { code: "CG", en: "Congo - Brazzaville", ar: "الكونغو - برازافيل" },
  { code: "CD", en: "Congo - Kinshasa", ar: "الكونغو - كينشاسا" },
  { code: "ZR", en: "Congo - Kinshasa", ar: "الكونغو - كينشاسا" },
  { code: "CK", en: "Cook Islands", ar: "جزر كوك" },
  { code: "CR", en: "Costa Rica", ar: "كوستاريكا" },
  { code: "CI", en: "Côte d’Ivoire", ar: "ساحل العاج" },
  { code: "HR", en: "Croatia", ar: "كرواتيا" },
  { code: "CU", en: "Cuba", ar: "كوبا" },
  { code: "AN", en: "Curaçao", ar: "كوراساو" },
  { code: "CW", en: "Curaçao", ar: "كوراساو" },
  { code: "CY", en: "Cyprus", ar: "قبرص" },
  { code: "CZ", en: "Czechia", ar: "التشيك" },
  { code: "DK", en: "Denmark", ar: "الدانمرك" },
  { code: "DJ", en: "Djibouti", ar: "جيبوتي" },
  { code: "DM", en: "Dominica", ar: "دومينيكا" },
  { code: "DO", en: "Dominican Republic", ar: "جمهورية الدومينيكان" },
  { code: "EC", en: "Ecuador", ar: "الإكوادور" },
  { code: "EG", en: "Egypt", ar: "مصر" },
  { code: "SV", en: "El Salvador", ar: "السلفادور" },
  { code: "GQ", en: "Equatorial Guinea", ar: "غينيا الاستوائية" },
  { code: "ER", en: "Eritrea", ar: "إريتريا" },
  { code: "EE", en: "Estonia", ar: "إستونيا" },
  { code: "SZ", en: "Eswatini", ar: "إسواتيني" },
  { code: "ET", en: "Ethiopia", ar: "إثيوبيا" },
  { code: "FK", en: "Falkland Islands", ar: "جزر فوكلاند" },
  { code: "FO", en: "Faroe Islands", ar: "جزر فارو" },
  { code: "FJ", en: "Fiji", ar: "فيجي" },
  { code: "FI", en: "Finland", ar: "فنلندا" },
  { code: "FR", en: "France", ar: "فرنسا" },
  { code: "FX", en: "France", ar: "فرنسا" },
  { code: "GF", en: "French Guiana", ar: "غويانا الفرنسية" },
  { code: "PF", en: "French Polynesia", ar: "بولينيزيا الفرنسية" },
  { code: "TF", en: "French Southern Territories", ar: "الأقاليم الجنوبية الفرنسية" },
  { code: "GA", en: "Gabon", ar: "الغابون" },
  { code: "GM", en: "Gambia", ar: "غامبيا" },
  { code: "GE", en: "Georgia", ar: "جورجيا" },
  { code: "DD", en: "Germany", ar: "ألمانيا" },
  { code: "DE", en: "Germany", ar: "ألمانيا" },
  { code: "GH", en: "Ghana", ar: "غانا" },
  { code: "GI", en: "Gibraltar", ar: "جبل طارق" },
  { code: "GR", en: "Greece", ar: "اليونان" },
  { code: "GL", en: "Greenland", ar: "غرينلاند" },
  { code: "GD", en: "Grenada", ar: "غرينادا" },
  { code: "GP", en: "Guadeloupe", ar: "غوادلوب" },
  { code: "GU", en: "Guam", ar: "غوام" },
  { code: "GT", en: "Guatemala", ar: "غواتيمالا" },
  { code: "GG", en: "Guernsey", ar: "غيرنزي" },
  { code: "GN", en: "Guinea", ar: "غينيا" },
  { code: "GW", en: "Guinea-Bissau", ar: "غينيا بيساو" },
  { code: "GY", en: "Guyana", ar: "غيانا" },
  { code: "HT", en: "Haiti", ar: "هايتي" },
  { code: "HM", en: "Heard & McDonald Islands", ar: "جزيرة هيرد وجزر ماكدونالد" },
  { code: "HN", en: "Honduras", ar: "هندوراس" },
  { code: "HK", en: "Hong Kong SAR China", ar: "هونغ كونغ الصينية (منطقة إدارية خاصة)" },
  { code: "HU", en: "Hungary", ar: "هنغاريا" },
  { code: "IS", en: "Iceland", ar: "آيسلندا" },
  { code: "IN", en: "India", ar: "الهند" },
  { code: "ID", en: "Indonesia", ar: "إندونيسيا" },
  { code: "IR", en: "Iran", ar: "إيران" },
  { code: "IQ", en: "Iraq", ar: "العراق" },
  { code: "IE", en: "Ireland", ar: "أيرلندا" },
  { code: "IM", en: "Isle of Man", ar: "جزيرة مان" },
  { code: "IL", en: "Israel", ar: "إسرائيل" },
  { code: "IT", en: "Italy", ar: "إيطاليا" },
  { code: "JM", en: "Jamaica", ar: "جامايكا" },
  { code: "JP", en: "Japan", ar: "اليابان" },
  { code: "JE", en: "Jersey", ar: "جيرسي" },
  { code: "JO", en: "Jordan", ar: "الأردن" },
  { code: "KZ", en: "Kazakhstan", ar: "كازاخستان" },
  { code: "KE", en: "Kenya", ar: "كينيا" },
  { code: "KI", en: "Kiribati", ar: "كيريباتي" },
  { code: "XK", en: "Kosovo", ar: "كوسوفو" },
  { code: "KW", en: "Kuwait", ar: "الكويت" },
  { code: "KG", en: "Kyrgyzstan", ar: "قيرغيزستان" },
  { code: "LA", en: "Laos", ar: "لاوس" },
  { code: "LV", en: "Latvia", ar: "لاتفيا" },
  { code: "LB", en: "Lebanon", ar: "لبنان" },
  { code: "LS", en: "Lesotho", ar: "ليسوتو" },
  { code: "LR", en: "Liberia", ar: "ليبيريا" },
  { code: "LY", en: "Libya", ar: "ليبيا" },
  { code: "LI", en: "Liechtenstein", ar: "ليختنشتاين" },
  { code: "LT", en: "Lithuania", ar: "ليتوانيا" },
  { code: "LU", en: "Luxembourg", ar: "لوكسمبورغ" },
  { code: "MO", en: "Macao SAR China", ar: "منطقة ماكاو الإدارية الخاصة" },
  { code: "MG", en: "Madagascar", ar: "مدغشقر" },
  { code: "MW", en: "Malawi", ar: "ملاوي" },
  { code: "MY", en: "Malaysia", ar: "ماليزيا" },
  { code: "MV", en: "Maldives", ar: "جزر المالديف" },
  { code: "ML", en: "Mali", ar: "مالي" },
  { code: "MT", en: "Malta", ar: "مالطا" },
  { code: "MH", en: "Marshall Islands", ar: "جزر مارشال" },
  { code: "MQ", en: "Martinique", ar: "جزر المارتينيك" },
  { code: "MR", en: "Mauritania", ar: "موريتانيا" },
  { code: "MU", en: "Mauritius", ar: "موريشيوس" },
  { code: "YT", en: "Mayotte", ar: "مايوت" },
  { code: "MX", en: "Mexico", ar: "المكسيك" },
  { code: "FM", en: "Micronesia", ar: "ميكرونيزيا" },
  { code: "MD", en: "Moldova", ar: "مولدوفا" },
  { code: "MC", en: "Monaco", ar: "موناكو" },
  { code: "MN", en: "Mongolia", ar: "منغوليا" },
  { code: "ME", en: "Montenegro", ar: "الجبل الأسود" },
  { code: "MS", en: "Montserrat", ar: "مونتسرات" },
  { code: "MA", en: "Morocco", ar: "المغرب" },
  { code: "MZ", en: "Mozambique", ar: "موزمبيق" },
  { code: "BU", en: "Myanmar (Burma)", ar: "ميانمار (بورما)" },
  { code: "MM", en: "Myanmar (Burma)", ar: "ميانمار (بورما)" },
  { code: "NA", en: "Namibia", ar: "ناميبيا" },
  { code: "NR", en: "Nauru", ar: "ناورو" },
  { code: "NP", en: "Nepal", ar: "نيبال" },
  { code: "NL", en: "Netherlands", ar: "هولندا" },
  { code: "NC", en: "New Caledonia", ar: "كاليدونيا الجديدة" },
  { code: "NZ", en: "New Zealand", ar: "نيوزيلندا" },
  { code: "NI", en: "Nicaragua", ar: "نيكاراغوا" },
  { code: "NE", en: "Niger", ar: "النيجر" },
  { code: "NG", en: "Nigeria", ar: "نيجيريا" },
  { code: "NU", en: "Niue", ar: "نيوي" },
  { code: "NF", en: "Norfolk Island", ar: "جزيرة نورفولك" },
  { code: "KP", en: "North Korea", ar: "كوريا الشمالية" },
  { code: "MK", en: "North Macedonia", ar: "مقدونيا الشمالية" },
  { code: "MP", en: "Northern Mariana Islands", ar: "جزر ماريانا الشمالية" },
  { code: "NO", en: "Norway", ar: "النرويج" },
  { code: "OM", en: "Oman", ar: "عُمان" },
  { code: "PK", en: "Pakistan", ar: "باكستان" },
  { code: "PW", en: "Palau", ar: "بالاو" },
  { code: "PS", en: "Palestinian Territories", ar: "الأراضي الفلسطينية" },
  { code: "PA", en: "Panama", ar: "بنما" },
  { code: "PG", en: "Papua New Guinea", ar: "بابوا غينيا الجديدة" },
  { code: "PY", en: "Paraguay", ar: "باراغواي" },
  { code: "PE", en: "Peru", ar: "بيرو" },
  { code: "PH", en: "Philippines", ar: "الفلبين" },
  { code: "PN", en: "Pitcairn Islands", ar: "جزر بيتكيرن" },
  { code: "PL", en: "Poland", ar: "بولندا" },
  { code: "PT", en: "Portugal", ar: "البرتغال" },
  { code: "PR", en: "Puerto Rico", ar: "بورتوريكو" },
  { code: "QA", en: "Qatar", ar: "قطر" },
  { code: "RE", en: "Réunion", ar: "روينيون" },
  { code: "RO", en: "Romania", ar: "رومانيا" },
  { code: "RU", en: "Russia", ar: "روسيا" },
  { code: "SU", en: "Russia", ar: "روسيا" },
  { code: "RW", en: "Rwanda", ar: "رواندا" },
  { code: "WS", en: "Samoa", ar: "ساموا" },
  { code: "SM", en: "San Marino", ar: "سان مارينو" },
  { code: "ST", en: "São Tomé & Príncipe", ar: "ساو تومي وبرينسيبي" },
  { code: "CQ", en: "Sark", ar: "سارك" },
  { code: "SA", en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
  { code: "SN", en: "Senegal", ar: "السنغال" },
  { code: "CS", en: "Serbia", ar: "صربيا" },
  { code: "RS", en: "Serbia", ar: "صربيا" },
  { code: "YU", en: "Serbia", ar: "صربيا" },
  { code: "SC", en: "Seychelles", ar: "سيشل" },
  { code: "SL", en: "Sierra Leone", ar: "سيراليون" },
  { code: "SG", en: "Singapore", ar: "سنغافورة" },
  { code: "SX", en: "Sint Maarten", ar: "سانت مارتن" },
  { code: "SK", en: "Slovakia", ar: "سلوفاكيا" },
  { code: "SI", en: "Slovenia", ar: "سلوفينيا" },
  { code: "SB", en: "Solomon Islands", ar: "جزر سليمان" },
  { code: "SO", en: "Somalia", ar: "الصومال" },
  { code: "ZA", en: "South Africa", ar: "جنوب أفريقيا" },
  { code: "GS", en: "South Georgia & South Sandwich Islands", ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية" },
  { code: "KR", en: "South Korea", ar: "كوريا الجنوبية" },
  { code: "SS", en: "South Sudan", ar: "جنوب السودان" },
  { code: "ES", en: "Spain", ar: "إسبانيا" },
  { code: "LK", en: "Sri Lanka", ar: "سريلانكا" },
  { code: "BL", en: "St. Barthélemy", ar: "سان بارتليمي" },
  { code: "SH", en: "St. Helena", ar: "سانت هيلينا" },
  { code: "KN", en: "St. Kitts & Nevis", ar: "سانت كيتس ونيفيس" },
  { code: "LC", en: "St. Lucia", ar: "سانت لوسيا" },
  { code: "MF", en: "St. Martin", ar: "سان مارتن" },
  { code: "PM", en: "St. Pierre & Miquelon", ar: "سان بيير ومكويلون" },
  { code: "VC", en: "St. Vincent & Grenadines", ar: "سانت فنسنت وجزر غرينادين" },
  { code: "SD", en: "Sudan", ar: "السودان" },
  { code: "SR", en: "Suriname", ar: "سورينام" },
  { code: "SJ", en: "Svalbard & Jan Mayen", ar: "سفالبارد وجان ماين" },
  { code: "SE", en: "Sweden", ar: "السويد" },
  { code: "CH", en: "Switzerland", ar: "سويسرا" },
  { code: "SY", en: "Syria", ar: "سوريا" },
  { code: "TW", en: "Taiwan", ar: "تايوان" },
  { code: "TJ", en: "Tajikistan", ar: "طاجيكستان" },
  { code: "TZ", en: "Tanzania", ar: "تنزانيا" },
  { code: "TH", en: "Thailand", ar: "تايلاند" },
  { code: "TL", en: "Timor-Leste", ar: "تيمور - ليشتي" },
  { code: "TP", en: "Timor-Leste", ar: "تيمور - ليشتي" },
  { code: "TG", en: "Togo", ar: "توغو" },
  { code: "TK", en: "Tokelau", ar: "توكيلاو" },
  { code: "TO", en: "Tonga", ar: "تونغا" },
  { code: "TT", en: "Trinidad & Tobago", ar: "ترينيداد وتوباغو" },
  { code: "TN", en: "Tunisia", ar: "تونس" },
  { code: "TR", en: "Türkiye", ar: "تركيا" },
  { code: "TM", en: "Turkmenistan", ar: "تركمانستان" },
  { code: "TC", en: "Turks & Caicos Islands", ar: "جزر توركس وكايكوس" },
  { code: "TV", en: "Tuvalu", ar: "توفالو" },
  { code: "UM", en: "U.S. Outlying Islands", ar: "جزر الولايات المتحدة النائية" },
  { code: "VI", en: "U.S. Virgin Islands", ar: "جزر فيرجن الأمريكية" },
  { code: "UG", en: "Uganda", ar: "أوغندا" },
  { code: "UA", en: "Ukraine", ar: "أوكرانيا" },
  { code: "AE", en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
  { code: "GB", en: "United Kingdom", ar: "المملكة المتحدة" },
  { code: "UK", en: "United Kingdom", ar: "المملكة المتحدة" },
  { code: "US", en: "United States", ar: "الولايات المتحدة" },
  { code: "UY", en: "Uruguay", ar: "أورغواي" },
  { code: "UZ", en: "Uzbekistan", ar: "أوزبكستان" },
  { code: "NH", en: "Vanuatu", ar: "فانواتو" },
  { code: "VU", en: "Vanuatu", ar: "فانواتو" },
  { code: "VA", en: "Vatican City", ar: "الفاتيكان" },
  { code: "VE", en: "Venezuela", ar: "فنزويلا" },
  { code: "VD", en: "Vietnam", ar: "فيتنام" },
  { code: "VN", en: "Vietnam", ar: "فيتنام" },
  { code: "WF", en: "Wallis & Futuna", ar: "جزر والس وفوتونا" },
  { code: "EH", en: "Western Sahara", ar: "الصحراء الغربية" },
  { code: "YD", en: "Yemen", ar: "اليمن" },
  { code: "YE", en: "Yemen", ar: "اليمن" },
  { code: "ZM", en: "Zambia", ar: "زامبيا" },
  { code: "RH", en: "Zimbabwe", ar: "زيمبابوي" },
  { code: "ZW", en: "Zimbabwe", ar: "زيمبابوي" },
];
